services:
  app:
    build:
      context: ./app  # Ruta del Dockerfile para la aplicaci贸n FastAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - deploy_network
    container_name: app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/clinica_veterinaria?authSource=admin  # URI de conexi贸n a MongoDB

  streamlit:
    build:
      context: ./streamlit  # Ruta del Dockerfile para la aplicaci贸n Streamlit
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "8501:8501"
    networks:
      - deploy_network
    container_name: streamlit

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    networks:
      - deploy_network
    container_name: mongodb
    command: mongod --quiet --auth  # Reducir los logs y habilitar autenticaci贸n

networks:
  deploy_network:
    driver: bridge