version: '3'

services:
  app:
    build: app/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: app
    volumes:
      - mis_datos:/var/lib/docker/volumes/aa-streamlit-fastapi_mis_datos/_data

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_LOG_LEVEL=2  # Configura el nivel de log de MongoDB
      - storage.wiredTiger.engineConfig.journalCompressor=zlib
    ports:
      - 27017:27017
    networks:
      - deploy_network
    container_name: mongodb

  streamlit:
    build: streamlit/
    depends_on:
      - app
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit
    volumes:
      - mis_datos:/var/lib/docker/volumes/aa-streamlit-fastapi_mis_datos/_data

networks:
  deploy_network:
    driver: bridge

volumes:
  mis_datos: