services:
  app:
    build:
      context: ./app  # Asegúrate de que el Dockerfile esté dentro de esta carpeta
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - deploy_network
    container_name: app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/?authSource=admin

  streamlit:
    build:
      context: ./streamlit  # Asegúrate de que el Dockerfile esté dentro de esta carpeta
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "8501:8501"
    networks:
      - deploy_network
    container_name: streamlit

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    networks:
      - deploy_network
    container_name: mongodb
    command: mongod --quiet --auth  # Reducir logs y habilitar autenticación

networks:
  deploy_network:
    driver: bridge